---
- name: Configure Jenkins server
  hosts: jenkins_servers
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-17-jre
        state: present

    - name: Add Jenkins repository key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        group: docker

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
